version: '3'

services:
  chat-service:
    image: paxapp/pax-chat:latest
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3001:3001
      - 9229:9229
    command: /bin/sh -c "npm install && npm audit fix && npm run-script build && npm start"
